# Generated by Django 3.1.5 on 2021-02-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_account',
            new_name='profile',
        ),
    ]
