# Generated by Django 3.1.5 on 2021-02-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210202_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='Transaction',
        ),
    ]
