# Generated by Django 3.1.5 on 2021-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210203_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
